a/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from b.admin import church_site


urlpatterns = [
    path('admin/', admin.site.urls),
    path('CHURCH/', church_site.urls),
    path('', include('b.urls')),
    # path('c', include('c.urls')),
    # path('accounts/', include('django.contrib.auth.urls'))
]
# if settings.DEBUG:
#     urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

b/urls.py
from django.urls import path
from . import views



app_name = 'b'


urlpatterns = [
    path('', views.Home, name='home'),
    path('UPLOADS/', views.upload, name='videos'),
    path("contact/", views.contact, name="contact"),
    path('SANCTUARY-KEEPERS/', views.Santuary, name='keepers'),
    path('TRANSPORTATION-UNIT/', views.Transport, name='transport'),
    path('welcome', views.Pastor_desk, name='pastor'),
    path('COMMUNION-SERVICE', views.Communion, name='communion'),
    path('JOIN-ME-IN-PRAYER/', views.PrayerView, name='pray'),
    path('Biblical-COUNSELling', views.Counselling, name='counsel'),
    path('ABOUT-US/', views.About, name='about'),
    path('I-AM-MORE-THAN-A-CONQUEROR/', views.Prophetic_Decleration, name='this-year'),
    path('Invite-a-friend/', views.Invitee, name='invite'),
    path('BREAKTHROUGH-TIME/', views.Testy, name='testimony'),
    path('WORD-OF-FAITH-BIBLE-INSTITUTE/', views.Wofbi, name='wofbi'),
    path('DOMINION-BOOKSHOP/', views.Books, name='book'),
    path('THE-MANDATE-PILLARS/', views.Pillars, name='faith'),
    path('THE-CHURCH-GROWTH-MANDATE/', views.Growth, name='church-growth'),
    path('GIVING-OUT', views.giving, name="giving"),
    path('MINISTRY-RESOURCES/', views.Resources, name='pdf'),
    path('MUSIC-MINISTRY/', views.choir, name='choir'),
    path('CHOIR-SONG', views.choirsong, name='songs'),
    path('VIGILANCE-MINISTRY/', views.security, name='security'),
    path('BEAUTIFYING-MINISTRY/', views.decorate, name='decorate'),
    path('CHILDREN-MINISTRY/', views.children, name='children'),
    path('PRAYER-MINISTRY/', views.prayerforce, name='prayerforce'),
    path('HOSPITALITY-MINISTRY/', views.hospitality, name='hospitality'),
    path('PROPHETIC-FOCUS/', views.Monthly, name='yt'),
    path('BOOKS-OF-THE-MONTH/', views.Book_of_Month, name='Bkm'),
    path('WINNERS-SATELLITE-FELLOWSHIP/', views.cell, name='wsf'),
    path('WEEK-OF-SPIRITUAL-EMPHASIS/', views.SpWE, name='week'),
    path('BELIEVERS-FOUNDATION-CLASS/', views.bfc, name='bfc'),
    path('MEDIA-CENTER/', views.Studio, name='studio'),
    path('USHERING-&-PROTOCOL/', views.ushering, name='usher'),
    path('PREACHINGS/', views.service, name='sunday'),
    path('WORD-OF-FAITH/', views.all_message, name='messages'), # messages or sms
    path('MESSAGE<int:id>', views.MDetail, name='detail'),
    path('all-category', views.all_category, name='all-category'),
    path('category<int:id>', views.category, name='category'),
    path('HARVESTER-&-FOLLOW-UP', views.Harvester, name='harvest'),
    path('GILEAD-TEAM', views.Gilead, name='gilead'),
    path('JOEL-COMPANY-INC', views.drama, name='joel'),
    path('DOMI/', views.domi, name='domi'),
    path('GALLERY', views.gal, name='gal')
    # path('ADE/', views.cool, name='ade'),
    # path('MINISTRY-PRAYER/', Prayer.as_view(), name='pd'),
    # path('MINISTRY-PRAYER/', views.Prayer, name='pd')
    # path('ABOUT US', views.About, name='about'),
    # path('ay', views.upload, name='upload' ),
    # path('archives', views.blog_view, name='archives'),
    # path('<int:id>/', views.detail_view, name='og'),
    # path('a', views.services, name='sss'),
    # path('cells', views.wsf, name='wsf_list'),
    # path('books', views.shop, name='book_list'),
    # path('media', views.studio, name='nice'),
    # path('halelluyah', views.tropics, name='wonder'),
    # path('congrat', views.topics, name='topics'),
    # path('mercy(?P<topic_id>\d+)$', views.topic, name='good'),
    # path('miracles(?P<tropic_id>\d+)$', views.tropic, name='no'),
    # path('yaf', views.Yaf, name='amen'),
    # path('wow', views.contact_form, name='back'),
    # path('woow', views.yafcontact, name='alayo'),
    # path('new', views.tops, name='new'),
    # path('(?P<pk>\d+)$', views.top, name='news')
]

b/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect, get_object_or_404
from .forms import PrayerForm, BookshopForm, choirForm
from django.views.generic import ListView, View
from .models import Praye, Counsel, Invite, Ivpg, Testimony, WOFBI, Bookshop, PDF, Choir, Security, Decoration, CHILDREN,\
    PF, HOSPITALITY, PROPHET_FOCUS, BOOKS_of_the_Months, Recommended_Books, WSF, SPIRITUAL, Recommended_Books_Time,\
    TECHNICAL, USHERING, Services, Category,  Video, SANCTUARY, TRANSPORTATION, HARVESTER, HEALTH_WORKERS, DRAMA,\
    ChoirPage1, ChoirPage2, HomeCarousel, ChoirSong, CA, Contact, Pastor_Desk
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib import messages



# from django.views.generic import TemplateView
# from django.core.files.storage import FileSystemStorage
# from .forms import BookForm, ContactForm, YafContactForm
# from .models import Carousel, Post, PostImage, Book, Video, Topic,  Tropic,Dentry, Bookshop, Contact, Now, YafContact
#
# from django.contrib import messages





#
def About(request):
    return render(request, 'b/aboutus.html')






def service(request):
    # first_sms = Services.objects.first()
    side_sms = Services.objects.all()
    three_category = Category.objects.all()
    context = {
        # 'first_sms' : first_sms,
        'side_sms' : side_sms,
        'three_category' : three_category
    }
    return  render(request, 'b/test.html', context)

def all_message(request):
    all_sms = Services.objects.all()
    context = {
        'all_sms': all_sms
    }
    return render(request, 'b/3.html', context)

def MDetail(request, id):
    sms = Services.objects.get(pk=id)
    # category = Category.objects.get(id=sms.category.id)
    # rel_name = Services.objects.filter(category=category) #.excluded(id=id)

    context = {
        'sms': sms,
        # 'rel_name': rel_name
    }
    return render(request, 'b/2.html', context)

def all_category(request):
    cats = Category.objects.all()
    context = {
        'cats' : cats,
    }
    return render(request, 'b/a.html', context)

def category(request, id):
    category = Category.objects.get(id=id)
    sms = Services.objects.filter(category=category)
    context = {
        'all_news': sms,
        'category': category,
    }
    return render(request, 'b/b.html', context)

def Transport(request):

    if request.method=='POST':
        full_name = request.POST.get('full_name', '')
        residence = request.POST.get('residence', '')
        email = request.POST.get('email', '')
        phone = request.POST.get('phone', '')
        city = request.POST.get('city', '')
        born_again = request.POST.get('born_again', '')
        joined_date = request.POST.get('joined_date', '')
        new_birth_date = request.POST.get('new_birth_date', '')
        occupation = request.POST.get('occupation', '')
        foundation_class = request.POST.get('foundation_class', '')
        job = request.POST.get('job', '')
        status = request.POST.get('status', '')
        message = request.POST.get('message', '')

        t = TRANSPORTATION (
            full_name=full_name,
            residence=residence,
            email=email,
            phone=phone,
            city=city,
            born_again=born_again,
            joined_date=joined_date,
            new_birth_date=new_birth_date,
            occupation=occupation,
            foundation_class=foundation_class,
            job=job,
            status=status,
            message=message
        )
        t.save()
        return redirect('b:this-year')
    else:
        return render(request, 'b/trans.html')

def Gilead(request):
    if request.method=='POST':
        full_name = request.POST.get('full_name', '')
        residence = request.POST.get('residence', '')
        email = request.POST.get('email', '')
        phone = request.POST.get('phone', '')
        city = request.POST.get('city', '')
        born_again = request.POST.get('born_again', '')
        joined_date = request.POST.get('joined_date', '')
        new_birth_date = request.POST.get('new_birth_date', '')
        occupation = request.POST.get('occupation', '')
        foundation_class = request.POST.get('foundation_class', '')
        job = request.POST.get('job', '')
        status = request.POST.get('status', '')
        message = request.POST.get('message', '')

        e = HEALTH_WORKERS (
            full_name=full_name,
            residence=residence,
            email=email,
            phone=phone,
            city=city,
            born_again=born_again,
            joined_date=joined_date,
            new_birth_date=new_birth_date,
            occupation=occupation,
            foundation_class=foundation_class,
            job=job,
            status=status,
            message=message
        )
        e.save()
        return redirect('b:this-year')
    else:
        return render(request, 'b/health.html')



def drama(request):
    if request.method=='POST':
        full_name = request.POST.get('full_name', '')
        residence = request.POST.get('residence', '')
        email = request.POST.get('email', '')
        phone = request.POST.get('phone', '')
        city = request.POST.get('city', '')
        born_again = request.POST.get('born_again', '')
        joined_date = request.POST.get('joined_date', '')
        new_birth_date = request.POST.get('new_birth_date', '')
        occupation = request.POST.get('occupation', '')
        foundation_class = request.POST.get('foundation_class', '')
        job = request.POST.get('job', '')
        status = request.POST.get('status', '')
        message = request.POST.get('message', '')

        e = DRAMA (
            full_name=full_name,
            residence=residence,
            email=email,
            phone=phone,
            city=city,
            born_again=born_again,
            joined_date=joined_date,
            new_birth_date=new_birth_date,
            occupation=occupation,
            foundation_class=foundation_class,
            job=job,
            status=status,
            message=message
        )
        e.save()
        return redirect('b:this-year')
    else:
        return render(request, 'b/joel.html')

def cool(request):
    return render(request, 'b/ade.html')

def domi(request):
    return render(request, 'b/domi.html')

def ushering(request):
    if request.method=='POST':
        full_name = request.POST.get('full_name', '')
        residence = request.POST.get('residence', '')
        email = request.POST.get('email', '')
        phone = request.POST.get('phone', '')
        city = request.POST.get('city', '')
        born_again = request.POST.get('born_again', '')
        joined_date = request.POST.get('joined_date', '')
        new_birth_date = request.POST.get('new_birth_date', '')
        occupation = request.POST.get('occupation', '')
        foundation_class = request.POST.get('foundation_class', '')
        job = request.POST.get('job', '')
        status = request.POST.get('status', '')
        message = request.POST.get('message', '')

        e = USHERING (
            full_name=full_name,
            residence=residence,
            email=email,
            phone=phone,
            city=city,
            born_again=born_again,
            joined_date=joined_date,
            new_birth_date=new_birth_date,
            occupation=occupation,
            foundation_class=foundation_class,
            job=job,
            status=status,
            message=message
        )
        e.save()
        return redirect('b:this-year')
    else:
        return render(request, 'b/usher.html')



def Home(request):
    img = HomeCarousel.objects.all()

    context = {
        'img':img
    }
    return render(request, 'b/d.html', context)

def Pillars(request):
    return render(request, 'b/pillar.html')

def Communion(request):
    return render(request, 'b/ara_ati_eje_JESU.html')

def cell(request):
    wsf = WSF.objects.all()
    context = {
        'wsf':wsf
    }
    return render(request, 'b/wsf.html', context)

def giving(request):
    a = CA.objects.all()

    context = {
        'a': a
    }
    return render(request, 'b/giv.html', context)


def bfc(request):
    return render(request, 'b/bfc.html')


def Studio(request):
    if request.method=='POST':
        full_name = request.POST.get('full_name', '')
        residence = request.POST.get('residence', '')
        email = request.POST.get('email', '')
        phone = request.POST.get('phone', '')
        city = request.POST.get('city', '')
        born_again = request.POST.get('born_again', '')
        joined_date = request.POST.get('joined_date', '')
        new_birth_date = request.POST.get('new_birth_date', '')
        occupation = request.POST.get('occupation', '')
        foundation_class = request.POST.get('foundation_class', '')
        job = request.POST.get('job', '')
        status = request.POST.get('status', '')
        message = request.POST.get('message', '')

        e = TECHNICAL (
            full_name=full_name,
            residence=residence,
            email=email,
            phone=phone,
            city=city,
            born_again=born_again,
            joined_date=joined_date,
            new_birth_date=new_birth_date,
            occupation=occupation,
            foundation_class=foundation_class,
            job=job,
            status=status,
            message=message
        )
        e.save()
        return redirect('b:this-year')
    else:
        return render(request, 'b/studio.html')

def SpWE(request):
    week = SPIRITUAL.objects.all()
    context = {
        'week': week
    }
    return render(request,'b/spiritual.html', context)


def Book_of_Month(request):
    recommended = Recommended_Books.objects.all()
    record = Recommended_Books_Time.objects.all()
    context = {
        'recommended': recommended,
        'record':record
    }

b/templates/b/a.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="row main-content">
  <div class="large-12 columns">
    <h3><b style="color:#fff">ALL CATEGORY</b></h3>
    <div class="row">
        {% for cat in cats %}
        <div class="card mb-3 shadow">
            <img src="/media/{{cat.category_image}}" alt="{{cat.title}}" class="card-img-top">
            <div class="card-body">
                <h5 class="card-title">{{cat.title}}</h5>
                <p class="card-text"><a href="{% url 'b:category' cat.id %}" class="btn btn-success col-12">VIEW</a></p>
            </div>
        </div>
       {% endfor %}
    </div>
  </div>
</div>






{% endblock content %}

b/templates/b/home.html
{% extends 'base.html' %}


{% load static %}
{% block content %}



{% block unit %}
    {% include 'b/pillars.html' %}
{% endblock unit %}


{% endblock content %}

b/templates/b/orin.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<title> MUSIC MINISTRY | Winners Chapel International - Total Garden | winnerschapeltg.org</title>


<div class="row">
  <div class="large-12 columns">
    <table>
      <thead>
        <tr>
          <th width="455">Available Resources</th>
          <th width="152"></th>
          <th width="182"></th>
          <th width="199">OPTION Button</th>
        </tr>
      </thead>
      <tbody>
        <tr class="closealldiv" id="showing0">
          {% for x in orin %}
          <td style="padding-left:25px;"><b>{{x.title}}</td>
          <td style="padding-left:25px;"> </td>
          <td style="padding-left:25px;"></td>
          <td style="padding-left:25px;"><a target="_blank" href="{{ x.song.url }}" class="button success">OPEN</a></td>
          {% endfor %}
        </tr>
      </tbody>
    </table>
<!--    <div id="plm" class="dynamic_pagination">Showing SONGS <span id="startofproduct_span">1</span>-<span id="lastofproduct_span">10</span> of <span id="totalnumberofproduct_span">25</span> <a id="pervious_button" style="cursor:pointer; display: none;" onclick="return next_pervious()">[Previous] </a> <a id="next_button" style="cursor:pointer;" onclick="return previous_next()">[Next]</a></div>-->
<!--    <input type="hidden" name="startofproduct" id="startofproduct" value="1"/>-->
<!--    <input type="hidden" name="lastofproduct" id="lastofproduct" value="10"/>-->
<!--    <input type="hidden" name="totalnumberofproduct" id="totalnumberofproduct" value="25"/>-->
<!--  </div>-->
</div>
</div>
{% endblock content %}

b/templates/b/page.html
<div class="">


              <span class="">
              {% if page.has_previous %}
              <a href="?page={{ page.previous_page_number }}">Previous</a>
              {% endif %}

              <span class="">
              Page {{ page.number }} of {{ page.paginator.num_pages }}.
              </span>

              {% if page.has_next %}
              <a href="?page={{ page.next_page_number }}">Next</a>
              {% endif %}
              </span>
    <br>
    <br>
    <br>

</div>

b/templates/b/unit.html
<!--{% load static %}-->
    <style>
.jcarousel-skin-tango .jcarousel-container-vertical {
    height: 409px;
    padding: 5px 10px 15px 30px;
	 font-family: "century gothic";
	 font-size:13px;
	/* color:#000;
	 background: #fff;*/
	 border: solid 1px #cccccc;
    color: #4e4e4e;
    background: #F2F2F2;
    overflow: hidden;
}

.jcarousel-skin-tango .jcarousel-clip {
    overflow: hidden;
}

.jcarousel-skin-tango .jcarousel-clip-vertical {
    height: 395px;
}

.jcarousel-skin-tango .jcarousel-item {
    height: 147x;
}

.jcarousel-skin-tango .jcarousel-item-placeholder {
    background: #fff;
    color: #000;
}

/**
 *  Vertical Buttons
 */
.jcarousel-skin-tango .jcarousel-next-vertical {
    position: absolute;
    bottom: 5px;
	 bottom: 5px;
    left: 0px;
    width: 340px;
    height: 14px;
    cursor: pointer;
    background: transparent url(./static/img/down.gif) no-repeat 0 0;
}

.jcarousel-skin-tango .jcarousel-prev-vertical {
    position: absolute;
    top: 5px;
    left: 0px;
    width: 340px;
    height: 14px;
    cursor: pointer;
    background: transparent url(./static/img/up.gif) no-repeat 0 0;
}

.jcarousel-skin-tango a
{
    font-weight:bold;
	text-decoration:none;
}

.jcarousel-skin-tango .ql-img
{
    padding-right: 10px;
    float: left;
    width: 90px;
    height: 68px;
}

.jcarousel-skin-tango li
{
	padding:15px 0 6px 0;
    border-bottom: 1px solid #517da6;
    /*min-height:100px;*/
}

.jcarousel-skin-tango li.last
{
	border-bottom:none;
	padding:10px 0 0 0;
}
</style>
<link rel="stylesheet" type="text/css" href="{% static 'js/jquery-ui.html' %}">
<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.jcarousel.min.js' %}"></script>


  <script type="text/javascript">

      function mycarousel_initCallback(carousel)
      {
      // Disable autoscrolling if the user clicks the prev or next button.
      carousel.buttonNext.bind('click', function() {
      carousel.startAuto(0);
      });

      carousel.buttonPrev.bind('click', function() {
      carousel.startAuto(0);
      });

      // Pause autoscrolling if the user moves with the cursor over the clip.
      carousel.clip.hover(function() {
      carousel.stopAuto();
      }, function() {
      carousel.startAuto();
      });
      };

    jQuery(document).ready(function() {
        jQuery('#qlink-carousel').jcarousel({
            auto: 4,
            wrap: 'circular',
            scroll: 1,
            vertical: true,
            animation: 1200,
            initCallback: mycarousel_initCallback
        });
    });

</script>
    <div style="width:375px">
 <div align="center">
 <img src="{% static 'img/banners/serviceGroupHeader.png' %}" alt="Service Group Header"/></div>

<div class=" jcarousel-skin-tango"><div class="jcarousel-container jcarousel-container-vertical" style="position: relative; display: block;"><div class="jcarousel-clip jcarousel-clip-vertical" style="position: relative;">
 <ul id="qlink-carousel" class="jcarousel jcarousel-list jcarousel-list-vertical" style="overflow: hidden; position: relative; top: -238px; margin: 0px; padding: 0px; left: 0px; height: 814px;">

      <li class="jcarousel-item jcarousel-item-vertical jcarousel-item-1 jcarousel-item-1-vertical" jcarouselindex="1" style="float: left; list-style: none;">
        <img src="{% static 'img/protocol-ic.png' %}" class="ql-img">
        <a href="{% url 'b:usher' %}"><b style="font-size:16px;">USHERS | PROTOCOL</b></a><br/>
       This team welcomes worshippers and directs them to their respective seats, maintain order during services and meetings...
      </li>

       <li class="jcarousel-item jcarousel-item-vertical jcarousel-item-2 jcarousel-item-2-vertical" jcarouselindex="2" style="float: left; list-style: none;">
       <img src="{% static 'img/decor.png' %}" class="ql-img">
        <a href="{% url 'b:decorate' %}"><b style="font-size:16px;">DECORATION UNIT</b></a><br/>
        This is a creative team with individual specialized skills that they bring on board to beatify Gods House...
      </li>

      <li class="jcarousel-item jcarousel-item-vertical jcarousel-item-3 jcarousel-item-3-vertical" jcarouselindex="3" style="float: left; list-style: none;">
        <img src="{% static 'img/kiddies.png' %}" class="ql-img">
         <a href="{% url 'b:children' %}"><b style="font-size:16px;">CHILDREN'S MINISTRY</b></a> <br/>
             This is a team of a colorful, energetic, entertaining and dynamic children ministers, focused on teaching the word of faith to children.
      </li>

      <li class="jcarousel-item jcarousel-item-vertical jcarousel-item-4 jcarousel-item-4-vertical" jcarouselindex="4" style="float: left; list-style: none;">
         <img src="{% static 'img/hosp.png' %}"class="ql-img">
         <a href="{% url 'b:hospitality' %}"><b style="font-size:16px;">HOSPITALITY TEAM</b></a> <br/>
             This team give the warm Winners welcome to worshippers, provide adequate Christian care during services...
             </li>

               <li class="jcarousel-item jcarousel-item-vertical jcarousel-item-4 jcarousel-item-4-vertical" jcarouselindex="4" style="float: left; list-style: none;">
         <img src="{% static 'img/drama-ic.png' %}"class="ql-img">
         <a href="../hospitality/index.html"><b style="font-size:16px;">THE JOEL COMPANY</b></a> <br/>
           This team propagate the gospel through drama to liberate worshipers from the oppressions of the devil...
             </li>

               <li class="jcarousel-item jcarousel-item-vertical jcarousel-item-4 jcarousel-item-4-vertical" jcarouselindex="4" style="float: left; list-style: none;">
         <img src="{% static 'img/sanctuary-ic.png' %}"class="ql-img">
         <a href="../sanctuary/index.html"><b style="font-size:16px;">SANCTUARY KEEPERS</b></a> <br/>
               This team  is responsible for maintaining a well organised and orderly use of the Sanctuary before, during and after Services... </li>


             <li class="jcarousel-item jcarousel-item-vertical jcarousel-item-5 jcarousel-item-5-vertical" jcarouselindex="5" style="float: left; list-style: none;">
                <img src="{% static 'img/evangelism.png' %}" class="ql-img">
                <a href="../harvesters_squad/index.html"><b style="font-size:16px;">HARVESTERS' SQUAD</b></a><br/>
                      This comprise ardent soul-wiinners who preach and teach the word of God with the utilization of tracts to win souls...
             </li>

            <li class="jcarousel-item jcarousel-item-vertical jcarousel-item-6 jcarousel-item-6-vertical" jcarouselindex="6" style="float: left; list-style: none;">
                   <img src="{% static 'img/akam.png' %}"class="ql-img">
                  <a href="../prayerForce/index.html"><b style="font-size:16px;">THE PRAYER FORCE</b></a> <br/>
                           The prayer team forms a formidable force within the Church for continuous spiritual ...
            </li>

         <li class="jcarousel-item jcarousel-item-vertical jcarousel-item-6 jcarousel-item-6-vertical" jcarouselindex="6" style="float: left; list-style: none;">
               <img src="{% static 'img/choir-banner.jpg' %}"  class="ql-img">
              <a href="../choir/index.html"><b style="font-size:16px;">CHOIR | PRAISE TEAM</b></a> <br/>
                      The choir leads the congregation into the high praises of God and ultimately his presence...
         </li>

         <li class="jcarousel-item jcarousel-item-vertical jcarousel-item-6 jcarousel-item-6-vertical" jcarouselindex="6" style="float: left; list-style: none;">
               <img src="{% static 'img/protocol-ic.png' %}" class="ql-img">
              <a href=""><b style="font-size:16px;">USHERS | PROTOCOL</b></a> <br/>
                This team welcomes worshippers and directs them to their respective seats, maintain order during services and meetings...
         </li>

         <li class="jcarousel-item jcarousel-item-vertical jcarousel-item-6 jcarousel-item-6-vertical" jcarouselindex="6" style="float: left; list-style: none;">
           <img src="{% static 'img/medical-ic.png' %}" class="ql-img">
            <a href=""><b style="font-size:16px;">THE MEDICAL TEAM</b></a> <br/>
                    Trained and certified medical professionals who are ready to respond to medical emergencies...
        </li>

        <li class="jcarousel-item jcarousel-item-vertical jcarousel-item-6 jcarousel-item-6-vertical" jcarouselindex="6" style="float: left; list-style: none;">
           <img src="{% static 'img/security-ic.png' %}"  class="ql-img">
            <a href=""><b style="font-size:16px;">TCU | SECURITY | CCU</b></a> <br/>
                     Responsible for routine protocol duties within the Church premises during services ...
        </li>

  </ul>
</div>
  <div class="jcarousel-prev jcarousel-prev-vertical" disabled="false" style="display:
   block;"></div><div class="jcarousel-next jcarousel-next-vertical" disabled="false" style="display: block;">
   </div>

    </div>



    <div id="rotator-tooltip" class="img-down" style="paddint-top:55px;"></div>        <br/>
        <br/>
        <br/>

        <br/>
        <br/>
        <br/> <br/>
       <img src="{% static 'img/banners/invitation.png' %}" alt="Invite a Friend" border="0" usemap="#Map"/>

      </div>
    </div>

b/templates/b/upload.html
{% extends 'base.html' %}


{% load static %}
{% block content %}

<div class="row main-content">
<!-- Main Content -->
<div class="large-12 columns">
 <div class="row">
  <!-- Row -->
     <div class="large-8 columns"> <br/>
        <table class="table">
          <thead>
            <tr>
                <th><h1>VIDEOS</h1></th>
            </tr>
          </thead>
          <tbody>
            {% for video in videos %}

                <tr>
                    <td>
                       <button>
                           <a href="{{ video.videofile.url }}" target="blank">
                            <h6>{{ video.name }}</h6>
                           </a>
                       </button>

                    </td>
                </tr>
            {% endfor %}
          </tbody>
        </table>
     </div>

    <br/>
    <div class="large-4 columns">
      <div class="clearfix"></div>
        <!-- End Panel -->


        {% block unit %} {% include 'b/unit.html' %}  {% endblock unit %}


    </div>

</div>


 <br>

<br clear="all">
<br>
  <!-- End Special Row -->
<meta name="viewport" content="width=device-width" />
<title>| STUDIO Winners Chapel International, Total Garden Ibadan | winnerschapeltotalgarden.org</title>
    {% endblock content %}